/*
 * This Code is edited by sun wukong @ 2016.01.03 16:35:26 CST 
 * 
 * Just feel free to use this code as you wish.
 * Any bug and ugly code, please notify me, thanks!
 *
 * Github https://githuc.com/maybe2009
 * Gmail  qtdssunwukong@gmail.com
 * 									-Auto Generated By UltiSnips
 */

#ifndef OK_FILEIO_INCLUDED
#define OK_FILEIO_INCLUDED

#include <string>
#include <fcntl.h>

#include <errno.h>
#include <iostream>
#include <sys/stat.h>
#include <boost/noncopyable.hpp>

#include "IOUtility.h"

namespace ok{
class FileWrite : public boost::noncopyable
{
public:
    FileWrite(const std::string filepath, int flags = O_WRONLY|O_APPEND|O_CREAT)
        : fd_(::open(filepath.c_str(), flags)),
          flags_(flags),
          isOpen_(false),
          filepath_(filepath),
          io_()    
    {
        if (fd_ >= 0)
        {
            FileWrite::chmod(S_IRUSR|S_IWUSR|S_IRGRP|S_IWGRP|S_IROTH);
            isOpen_ = true;
        }
    }
    
    ~FileWrite()
    {
        if (isOpen_)
        {
            close(fd_);
        }
    }

public:
    size_t write(const std::string& content)
    {
        if (fd_ >= 0)
        {
            return io_.writeN(fd_, content.c_str(), content.size());  
        }
        else
        {
            std::cout << "Not Open" << std::endl;
        }
        return -1;
    }

private:
    void chmod(mode_t mode)
    {
        ::chmod(filepath_.c_str(), mode);
    }

private:
    int             fd_;
    int             flags_;
    bool            isOpen_;
    std::string     filepath_;     
    IOUtility       io_;
};

};


#endif /* ifndef OK_FILEIO_INCLUDED */
