/*
 * This Code is edited by sun wukong @ 2016.01.03 15:25:56 CST 
 * 
 * Just feel free to use this code as you wish.
 * Any bug and ugly code, please notify me, thanks!
 *
 * Github https://githuc.com/maybe2009
 * Gmail  qtdssunwukong@gmail.com
 * 									-Auto Generated By UltiSnips
 */

#ifndef OK_FILEUTILITY_INCLUDED
#define OK_FILEUTILITY_INCLUDED

#include <stdio.h>
#include <unistd.h>

#define E_EOF       0
#define E_READ      -1

class IOUtility
{
public:
    size_t readN(int fd, void* buf, size_t n);
    size_t writeN(int fd, const void* buf, size_t n);
private:
    int err_;
};

size_t IOUtility::
readN(int fd, void* buf, size_t n)
{
    size_t already, target, this_read;
    
    already = 0;
    target = n;
    this_read = 0;
    
    while (target > already)
    {
        this_read = read(fd, buf, target - already);
        if (this_read > 0)
        {
            already += this_read;
        }
        else
        {
            break;
        }
    } 

    return already;   
}

size_t IOUtility::
writeN(int fd, const void * buf, size_t n)
{
    size_t already, target, this_write;
    
    already = 0;
    target = n;
    this_write = 0;
    
    while (target > already)
    {
        this_write = write(fd, buf, target - already);
        if (this_write > 0)
        {
            already += this_write;
        }
        else
        {
            break;
        }
    }
    
    return already;
}
#endif /* ifndef OK_FILEUTILITY_INCLUDED*/
