/*
 * This Code is edited by sun wukong @ 2015.12.18 17:49:36 CST 
 * 
 * Just feel free to use this code as you wish.
 * Any bug and ugly code, please notify me, thanks!
 *
 * Github https://githuc.com/maybe2009
 * Gmail  qtdssunwukong@gmail.com
 * 									-Auto Generated By UltiSnips
 */

#ifndef AK_SPINLOCK_HPP
#define AK_SPINLOCK_HPP 
#include <pthread.h>

/*********************************************************************** 
      SpinLock Declaration
************************************************************************/ 
namespace ok{
class SpinLock{
public:
    SpinLock();
    ~SpinLock();
public:
    int tryLock();
    int lock();
    int unlock();
private:
    pthread_spinlock_t splock;
};

/*********************************************************************** 
      SpinLock Definition
************************************************************************/ 
SpinLock::
SpinLock()
{
    pthread_spin_init(&splock, PTHREAD_PROCESS_SHARED);
}

SpinLock::
~SpinLock()
{
    pthread_spin_destroy(&splock);
}

int SpinLock::
tryLock()
{
    return pthread_spin_trylock(&splock);
}

int SpinLock::
lock()
{
    return pthread_spin_lock(&splock);
}

int SpinLock::
unlock()
{
    return pthread_spin_unlock(&splock);
}
};
#endif /* ifndef AK_SPINLOCK_HPP */


