/*
 * This Code is edited by sun wukong @ 2015.12.18 17:51:13 CST 
 * 
 * Just feel free to use this code as you wish.
 * Any bug and ugly code, please notify me, thanks!
 *
 * Github https://githuc.com/maybe2009
 * Gmail  qtdssunwukong@gmail.com
 * 									-Auto Generated By UltiSnips
 */

#ifndef AK_THREADBARRIER_HPP
#define AK_THREADBARRIER_HPP 
#include <pthread.h>

/*********************************************************************** 
      ThreadBarrier Declaration
************************************************************************/ 
namespace ok{
class ThreadBarrier{
public:
    ThreadBarrier(int val);
    ~ThreadBarrier();
    int wait();
public:
private:
    int count;
    pthread_barrier_t barrier;
};

/*********************************************************************** 
      ThreadBarrier Definition
************************************************************************/ 
ThreadBarrier::
ThreadBarrier(int val) : count(val)
{
    pthread_barrier_init(&barrier, NULL, count);
}

int ThreadBarrier::
wait()
{
    return pthread_barrier_wait(&barrier);
}

ThreadBarrier::


ThreadBarrier::
~ThreadBarrier()
{
    pthread_barrier_destroy(&barrier);
}
};
#endif /* ifndef AK_THREADBARRIER_HPP */


